"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0QuWlsTYjKX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useState } from "react";

export default function CreateEvent() {
  const [isTagsOpen, setIsTagsOpen] = useState(false);
  const [isLinksOpen, setIsLinksOpen] = useState(false);

  return (
    <div className="flex flex-col gap-8 p-6 sm:p-10">
      <section className="grid gap-4">
        <div className="grid gap-2">
          <h2 className="text-2xl font-bold">New Event Details</h2>
          <p className="text-muted-foreground">
            Fill out the details to create your upcoming event.
          </p>
        </div>
        <Card>
          <CardContent className="grid gap-6">
            <div className="grid gap-2">
              <Label htmlFor="title">Event Title</Label>
              <Input id="title" placeholder="Enter event title" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="description">Event Description</Label>
              <Textarea
                id="description"
                placeholder="Enter event description"
                rows={4}
              />
            </div>
            <div className="grid gap-2">
              <Label>Event Image</Label>
              <div className="flex items-center gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Event Image"
                  className="rounded-md max-h-96"
                />
                <Button variant="outline">Upload Image</Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>
      <section className="grid gap-4">
        <div className="grid gap-2">
          <h2 className="text-2xl font-bold">Venue Details</h2>
          <p className="text-muted-foreground">
            Provide the details of the venue for your event.
          </p>
        </div>
        <Card>
          <CardContent className="grid gap-6">
            <div className="grid gap-2">
              <Label htmlFor="venue">Venue Name</Label>
              <Input id="venue" placeholder="Enter venue name" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="address">Venue Address</Label>
              <Textarea
                id="address"
                placeholder="Enter venue address"
                rows={3}
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="details">Venue Details</Label>
              <Textarea
                id="details"
                placeholder="Enter any additional venue details"
                rows={3}
              />
            </div>
          </CardContent>
        </Card>
      </section>

      <section className="grid gap-4">
        <div className="grid gap-2">
          <h2 className="text-2xl font-bold">Ticket Details</h2>
          <p className="text-muted-foreground">
            Set up the ticket types and pricing for your event.
          </p>
        </div>
        <Card>
          <CardContent className="grid gap-6">
            <div className="grid gap-2">
              <Label htmlFor="ticket-type">Ticket Type</Label>
              <Input id="ticket-type" placeholder="Enter ticket type" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="ticket-price">Ticket Price</Label>
              <Input
                id="ticket-price"
                type="number"
                placeholder="Enter ticket price"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="ticket-availability">Ticket Availability</Label>
              <Input
                id="ticket-availability"
                type="number"
                placeholder="Enter ticket availability"
              />
            </div>
          </CardContent>
        </Card>
      </section>
      <section className="grid gap-4">
        <div className="grid gap-2">
          <h2 className="text-2xl font-bold">Extra Details</h2>
          <p className="text-muted-foreground">Provide the details.</p>
        </div>
        <Card>
          <CardContent className="grid gap-6">
            <div className="grid gap-2">
              <Label htmlFor="tags">Tags</Label>
              <div className="flex items-center gap-4">
                <Button
                  onClick={() => setIsTagsOpen(!isTagsOpen)}
                  variant="outline"
                >
                  Add Tags
                </Button>
                {isTagsOpen && (
                  <div className="grid gap-2">
                    <Input placeholder="Enter tag" />
                    <Input placeholder="Enter tag" />
                    <Input placeholder="Enter tag" />
                  </div>
                )}
              </div>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="links">Links</Label>
              <div className="flex items-center gap-4">
                <Button
                  onClick={() => setIsLinksOpen(!isLinksOpen)}
                  variant="outline"
                >
                  Add Links
                </Button>
                {isLinksOpen && (
                  <div className="grid gap-2">
                    <Input placeholder="Enter link" />
                  </div>
                )}
              </div>
            </div>
          </CardContent>
        </Card>
      </section>
      <Button className="justify-self-end mt-5">Create Event</Button>
    </div>
  );
}
